config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :tokens, only: [:index, :create]
    resources :history, only: [:index, :create]
  end

  resources :user_authentications, path: '/account/authentications'

  # User settings
  match '/settings' => 'users#edit', via: [:get], as: :user_settings
  match '/settings' => 'users#update', via: [:put]

  # User profile
  resources :users, path: '/u', only: [:show], as: :user_profile, constraints: { id: /[A-Za-z0-9\.\-\_]+?/, format: /json/ } do
    get '/:date', action: :show, as: :dated, on: :member
  end

  # Omniauth
  match '/auth/:provider/callback' => 'user_authentications#create', via: [:get, :post]
  match '/auth/failure' => 'user_authentications#failure', via: [:get, :post]
  match '/auth/:provider' => 'user_authentications#blank', via: [:get], as: :authenticate

  # User Sessions
  get '/login' => 'user_sessions#new', as: :login
  get '/signup' => 'user_sessions#new', as: :signup, welcome: true
  match '/logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  # Web Sites
  resources :web_sites, path: '/s', only: [:index, :show], constraints: { id: /[A-Za-z0-9\.\-]+?/, format: /json/} do
    get '/:date', action: :show, as: :dated, on: :member
  end

  # Share success
  match '/share/:id/success' => 'static_pages#show', via: [:get], page: 'share_success', as: :share_success

  # Static pages routing, use StaticPage to check if exists as constraint
  match '/home/:date' => 'static_pages#show', via: [:get], page: 'home', as: :dated_everyone
  match '/*page' => 'static_pages#show', as: :static_page, constraints: StaticPage.new, via: [:get]

  # Specialized shortcodes
  match '/*code' => 'static_pages#short_code', as: :short_code, constraints: ShortCode.new, via: [:get]

  root to: 'static_pages#show', page: 'home'

end


ColorCamp::Application.routes.named_routes.url_helpers_module.module_eval do

  {
    # Social Media URLs
    facebook_url:           'https://facebook.com/mycolortoday',
    twitter_url:            'https://twitter.com/mycolortoday',
    instagram_url:          'http://instagram.com/mycolortoday',
    email_url:              'hello@mycolor.today',
    amazon_book_url:        'javascript:alert("The book will be available soon on Amazon. Check back in a few days.")',
    # amazon_book_url:        '/amazonbook', # short code referral tracking
    lulu_book_url:          '/lulubook', # short code referral tracking
    lulu_ebook_url:         '/luluebook', # short code referral tracking
    link_book_url:          'http://linkeditions.tumblr.com/gregleuch',

  }.each do |name,url|
    define_method(name){ url }
  end

end

app/models/static_page.rb
class StaticPage

  attr_accessor :data


  def initialize(p={}, format=nil)
    @page, @format = p[:page], format || p[:format]
    @data = {}
  end

  def matches?(r)
    return false if r.path_parameters[:page].blank?
    @page, @format = r.path_parameters[:page], r.path_parameters[:format]
    self.exists?
  end

  def file; (!self.page.blank? ? "static_pages/#{self.page}" : nil).downcase; end
  def page; @page.gsub(/\-/m, '_').downcase; end
  def page_method; @page.gsub(/\/|\-/m, '_').downcase; end
  def format; @format || 'html'; end

  def exists?(format=nil)
    return false if self.page.blank?
    return self.exists_for? || self.exists_for?('.haml') || self.exists_for?('.haml',:html)
  end

  def load_json_data(format=nil)
    return nil unless self.page.present? && self.exists_for?(nil,:json)
    self.data = File.read(self.fpath(nil,:json))# rescue nil
  end

  def self.available_pages(f=:html)
    Dir.glob("app/views/static_pages/*.#{f.to_s}.haml").map{|f| File.basename(f).split('.')[0]}
  end


protected

  def fpath(suffix=nil, format=nil)
    File.join(Rails.root, "app/views/static_pages/#{self.page}.#{format || self.format}#{suffix}")
  end

  def exists_for?(suffix=nil, format=nil)
    f = self.fpath(suffix, format)
    return false unless f.match(/app\/views\/static_pages\//) # dirup hack prevention
    File.exists?(f) && File.readable?(f)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :load_resource, only: [:show]
  before_filter :load_short_code, only: [:short_code]

  set_pagination_headers :colors, only: [:show]

  def show
    @_static_page_options = {}

    respond_to do |format|
      format.html {
        trigger_actions

        @body_classes << 'static-page' << "page-#{@page.page.gsub(/\/|\-/m, '_').gsub(/("|')/m, '')}"
        render @page.file, @_static_page_options unless performed?
      }
      format.json {
        trigger_actions
        json = JSON.parse(@page.data) rescue nil
        render json: json || @page.data, callback: params[:callback] unless performed?
      }
      format.any { render_not_found }
    end
  end

  def home
    if current_user?
      render_user_channel(current_user)
    else
      render_everyone_channel
    end
  end
  alias_method :svg, :home

  def load_data
    @page.load_json_data
  end

  def everyone
    render_everyone_channel
  end

  def short_code
    respond_to do |format|
      format.html {
        @code.track!(session: session.id, user: current_user && current_user.uuid, referrer: request.referer)
        redirect_to @code.url
      }
      format.json {
        render json: @code.to_api, callback: params[:callback] unless performed?
      }
      format.any { render_not_found }
    end
  end


protected

  def load_resource
    @page = StaticPage.new(params)
    raise ActiveRecord::RecordNotFound unless @page.exists?
  end

  def load_short_code
    @code = ShortCode.new(params)
    raise ActiveRecord::RecordNotFound unless @code.exists?
  end

  def trigger_actions
    begin
      send(@page.page_method)
    rescue ActiveRecord::RecordNotFound => err
      raise err
    rescue => err
      nil
    end if respond_to?(@page.page_method)
  end

end

app/views/static_pages/about.html.haml
- @page_title = t('about.title')
- @page_share_title = t('about.title')

app/views/static_pages/everyone.html.haml
- @canonical_url = static_page_url(:everyone)
- @page_title = t('everyone.title')
- @page_meta_description = t('everyone.description')
- @page_share_title = t('everyone.share.title')
- @page_share_description = t('everyone.share.description')

:coffee
  @ColorInitialProps.channel = #{ {viewType: :everyone, url: root_url, channel: 'everyone'}.to_json }

app/views/static_pages/home.html.haml
- #

app/views/static_pages/install.html.haml
- @page_title = t('install.title')
- @page_share_title = t('install.title')

app/views/static_pages/privacy.html.haml
- @page_title = t('privacy.title')
- @page_share_title = t('privacy.title')

app/views/static_pages/share_success.html.haml
- @disable_react = true
- @page_meta_robots = 'noindex,follow'

:coffee
  ga 'send', 'event', 'Share', '#{params[:id].to_s.capitalize}', 'Success'

  try
    window.close()
  catch e
    #

  setTimeout ->
    window.location.href = '#{root_url}'
  , 500

app/views/static_pages/svg.html.haml
%article
  %section
    :css
      svg#page-colors-list {position: fixed; top: 0; left: 0; bottom: 0; right: 0;}

    %svg#page-colors-list{'data-channel' => 'everyone', width: '100%', height: '100%', version: '1.1', xmlns: 'http://www.w3.org/2000/svg'}
      %defs
        %linearGradient#page-color-gradient{x1: 0, x2: 0, y1: 0, y2: 1}
          - unless @latest_colors.blank?
            - ct = @latest_colors.count.to_f
            - @latest_colors.each_with_index do |color,i|
              %stop.color{offset: "#{100 * (i / (ct-1))}%", 'stop-color' => "##{color.hex_color}", 'data-uuid' => color.uuid, 'data-rgb-color' => color.rgb_color}
      %rect{x: 0, y: 0, rx: 0, ry: 0, width: '100%', height: '100%', fill: 'url(#page-color-gradient)'}

app/views/static_pages/terms.html.haml
- @page_title = t('privacy.title')
- @page_share_title = t('privacy.title')